name: action-deploiement-config

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: rg4amia/common-laravel-ci/.github/workflows/common-deploy-laravel.yml@main
    with:
      environment: dev
      channel_id: ${{ vars.CHANNEL_ID }}
      github_actor: ${{ github.actor }}
      repo_github: ${{ vars.REPO_GITHUB }}
      branch_repo: 'develop'
      repo_name_host: 'e-stage'
      version_php: '8.1'
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
