name: Reusable Workflow Example
on:
  workflow_call:
    inputs:
      sonar_host:
        required: true
        type: string
      environment:
        required: true
        type: string
      channel_id:
        required: true
        type: string
      github_actor:
        required: true
        type: string
      repo_github:
        required: true
        type: string
      branch_repo:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      HOST:
        required: true
      USERNAME:
        required: true
      KEY:
        required: true
      PORT:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: environment
        run: |
          echo "${{ inputs.environment }} environment"
      - name: Sonar host
        run: |
          echo "Sonar url: ${{ inputs.sonar_host }}"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Installer les dependences
        run: composer install --prefer-dist --no-interaction
      - name: Copy file .env.exemple to .env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Execution des tests
        run: |
            echo "Execution des tests"
      - name: Deploy to ${{ inputs.environment }}
        if: success()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su
            set -e
            echo "Deploying application ..."
            cd /var/www/html/gestage/
            sudo git pull origin ${{ inputs.branch_repo }}
            (php artisan down) || true
            composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader
            php artisan migrate --force
            sudo chmod 777 -R /var/www/html/gestage/bootstrap/cache/
            sudo chmod 777 -R /var/www/html/gestage/storage/
            php artisan optimize
            php artisan storage:link
            echo "" | sudo service php8.1-fpm reload
            php artisan up
            echo "Application deployed!"
      - name: Post to a Slack channel
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ inputs.channel_id }}
          slack-message: "GitHub build result: ${{ job.status }}\n${{ inputs.github_actor }}\n${{ runner.os }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


