name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      channel_id:
        required: true
        type: string
      github_actor:
        required: true
        type: string
      repo_github:
        required: true
        type: string
      branch_repo:
        required: true
        type: string
      version_php:
        required: true
        type: string
      dependencyTrackProjetName:
        #required: true
        type: string
      dependencyTrackVersion:
        #required: true
        type: string
      repo_name_host:
        required: true
        type: string
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true
      KEY:
        required: true
      PORT:
        required: true
      DEPENDENCY_TRACK_API_KEY:
        #required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.version_php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-interaction

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Execute tests
        run: echo "Executing tests"

      - name: Post to a Slack channel
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          channel: ${{ inputs.channel_id }}
          text: "GitHub build result: ${{ job.status }}\n${{ inputs.github_actor }}\n${{ runner.os }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🎉‼️🏃🏽Deploy to production 🚚
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo usermod -a -G apache ${{ secrets.USERNAME }}
            sudo chown -R ${{ secrets.USERNAME }}:apache /var/www/html/${{ inputs.repo_name_host }}
            chmod +x server_deploy.sh
            cd /var/www/html/${{ inputs.repo_name_host }} && ./server_deploy.sh ${{ inputs.branch_repo }}
            sudo chown -R apache:apache ${{ inputs.repo_name_host }}
            sudo chmod -R 755 ${{ inputs.repo_name_host }}

      - name: Post to a Slack channel
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          channel: ${{ inputs.channel_id }}
          text: "GitHub build result: ${{ job.status }}\n${{ inputs.github_actor }}\n${{ runner.os }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
